import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
import argparse
import logging
import json
import numpy as np
import torch
from PIL import Image
from tqdm.auto import tqdm
from diffusers import DDIMScheduler 

from lawdis.lawdis_macro_pipeline import LawDISMacroPipeline

import math
import torch.nn as nn
class LatentDepthPredictor(nn.Module):
    def __init__(self, in_channels=8 + 256, out_channels=4, time_dim=256): 
        super().__init__()
        self.time_embed = nn.Sequential(
            nn.Linear(time_dim, time_dim),
            nn.SiLU(),
            nn.Linear(time_dim, time_dim),
        )
        self.net = nn.Sequential(
            nn.Conv2d(in_channels, 128, 3, padding=1),
            nn.GroupNorm(32, 128), nn.SiLU(),
            nn.Conv2d(128, 256, 3, padding=1),
            nn.GroupNorm(32, 256), nn.SiLU(),
            nn.Conv2d(256, 128, 3, padding=1),
            nn.GroupNorm(32, 128), nn.SiLU(),
            nn.Conv2d(128, out_channels, 3, padding=1)
        )
    def forward(self, z_t, latent_image, timesteps):
        half_dim = 256 // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, dtype=torch.float32, device=timesteps.device) * -emb)
        emb = timesteps.float()[:, None] * emb[None, :]
        emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=1)
        if 256 % 2 == 1:
            emb = torch.nn.functional.pad(emb, (0, 1, 0, 0))
        t_emb = self.time_embed(emb) 
        t_map = t_emb[:, :, None, None].repeat(1, 1, z_t.shape[2], z_t.shape[3])
        x = torch.cat([latent_image, z_t, t_map], dim=1) 
        return self.net(x)


if "__main__" == __name__:
    logging.basicConfig(level=logging.INFO)
    # -------------------- Arguments --------------------
    parser = argparse.ArgumentParser(
        description="Use LawDIS in macro mode for language-guided DIS with Depth Guidance."
    )
    parser.add_argument("--checkpoint", type=str, default="stable-diffusion-2")
    parser.add_argument("--input_rgb_dir", type=str, default="data/DIS5K")
    parser.add_argument("--subset_name", type=str, default="DIS-TE3")
    parser.add_argument("--prompt_dir", type=str, default='data/json')
    parser.add_argument("--output_dir", type=str, default="output/output-macro")
    
    parser.add_argument("--depth_dir", type=str, default=None, help="Path to TE3 depth maps generated by Depth-Anything-V2.")
    parser.add_argument("--guidance_model_path", type=str, default=None, help="Path to the trained f_phi checkpoint (.pth).")
    parser.add_argument("--guidance_scale", type=float, default=100.0, help="Scale factor cho classifier guidance.")

    parser.add_argument("--denoise_steps", type=int, default=20, help="Diffusion denoising steps. Khuyến cáo >= 20.")
    parser.add_argument("--half_precision", "--fp16", action="store_true")
    parser.add_argument("--processing_res", type=int, default=1024)
    parser.add_argument("--resample_method", choices=["bilinear", "bicubic", "nearest"], default="bilinear")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--batch_size", type=int, default=0)
    parser.add_argument("--vae_checkpoint", type=str, default=None)

    args = parser.parse_args()

    # -------------------- Preparation --------------------
    output_dir = os.path.join(args.output_dir, args.subset_name)
    os.makedirs(output_dir, exist_ok=True)
    logging.info(f"output dir = {output_dir}")

    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
    logging.info(f"device = {device}")

    prompt_path = os.path.join(args.prompt_dir, args.subset_name + '.json')
    with open(prompt_path, "r") as f:
            filenames = [(json.loads(line)['img'], json.loads(line)['prompt']) for line in f]
            
    if len(filenames) > 0:
        logging.info(f"Found {len(filenames)} images")
    else:
        logging.error(f"No image found.")
        exit(1)

    # -------------------- Model Loading --------------------
    dtype = torch.float16 if args.half_precision else torch.float32
    variant = "fp16" if args.half_precision else None

    # Load Base Pipeline
    pipe: LawDISMacroPipeline = LawDISMacroPipeline.from_pretrained(
        args.checkpoint, variant=variant, torch_dtype=dtype
    )

    pipe.scheduler = DDIMScheduler.from_pretrained(args.checkpoint, subfolder="scheduler")
    print("Switched scheduler to DDIMScheduler for Multi-step Guidance.")

    if args.vae_checkpoint:
        pipe.vae.load_state_dict(torch.load(args.vae_checkpoint, map_location=device))
        pipe.vae.eval()
        print(f"Loaded VAE checkpoint: {args.vae_checkpoint}")

    # LOAD GUIDANCE MODEL
    if args.guidance_model_path:
        f_phi = LatentDepthPredictor().to(device)
        f_phi.load_state_dict(torch.load(args.guidance_model_path, map_location=device))
        f_phi.eval()
        f_phi = f_phi.to(dtype)
        
        if args.half_precision:
            f_phi = f_phi.to(dtype)
            
        pipe.depth_predictor = f_phi
        print(f"✅ Đã load Guidance Model từ: {args.guidance_model_path}")
    else:
        pipe.depth_predictor = None
        print("⚠️ Không tìm thấy guidance_model_path, sẽ chạy inference bình thường (không có depth guidance).")

    pipe = pipe.to(device)

    # -------------------- Inference Loop --------------------
    os.makedirs(output_dir, exist_ok=True)

    for idx, filename in enumerate(tqdm(filenames, desc="Estimating dis")):
        img_name = filename[0]
        prompt = filename[1]
        
        rgb_path = os.path.join(args.input_rgb_dir, img_name)
        rgb_name_base = os.path.splitext(os.path.basename(rgb_path))[0]
        png_save_path = os.path.join(output_dir, f"{rgb_name_base}.png")

        if os.path.exists(png_save_path):
            continue

        input_image = Image.open(rgb_path)

        target_depth_img = None
        if args.depth_dir:
            depth_path = os.path.join(args.depth_dir, img_name)
            if not os.path.exists(depth_path):
                depth_path = os.path.join(args.depth_dir, f"{rgb_name_base}.png")
                
            if os.path.exists(depth_path):
                target_depth_img = Image.open(depth_path)
            else:
                logging.warning(f"Không tìm thấy file depth cho {img_name} tại {depth_path}")

        generator = torch.Generator(device=device).manual_seed(args.seed) if args.seed else None

        # Predict dis
        dis_pred = pipe(
            input_image=input_image,
            target_depth=target_depth_img,
            guidance_scale=args.guidance_scale,
            prompt=prompt,
            denoising_steps=args.denoise_steps,
            processing_res=args.processing_res,
            batch_size=args.batch_size,
            show_progress_bar=False,
            resample_method=args.resample_method,
            generator=generator
        )

        # Save
        dis_to_save = (dis_pred * 255.0).astype(np.uint8)
        Image.fromarray(dis_to_save).save(png_save_path, mode="L")